name: New WordPress.org release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  tag:
    name: New release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@54bd289b8525fd23a5c365ec369185f2966529c2 # 2.3.0
        env:
          SLUG: live-weather-station
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
