ame: Deploy Weather Station to WordPress.org
on:
  push:
    tags:
      - "*"
jobs:
  tag:
    name: New Release
    runs-on: ubuntu-latest
    steps:
      - name: WordPress Plugin Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLUG: live-weather-station
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
